---
- name: Deploy Personal Site
  hosts: all
  any_errors_fatal: true
  vars:
    global:
      timezone:
        name: America/Chicago
      docker_registry:
        credentials: "{{ lookup('env', 'DOCKER_REGISTRY_CREDENTIALS') }}"
      kubernetes:
        config: /etc/rancher/k3s/k3s.yaml
    app:
      namespace: "{{ lookup('env', 'K8S_NAMESPACE') }}"
      name: "{{ lookup('env', 'APP_NAME') }}"
      image: "{{ lookup('env', 'APP_IMAGE') }}"
      hostname: "{{ lookup('env', 'APP_HOSTNAME') }}"
  tasks:
    - name: Install pip packages
      pip:
        name: kubernetes

    - name: Create directory to upload k8s config to
      file:
        path: /root/deployments
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Upload k8s config
      template:
        src: app.yml.j2
        dest: /root/deployments/app.yml
        owner: root
        group: root
        mode: 0644

    - name: Load app to k8s
      k8s:
        kubeconfig: "{{ global.kubernetes.config }}"
        src: /root/deployments/app.yml
        state: present

    - name: Remove k8s config
      ansible.builtin.file:
        path: /root/deployments/app.yml
        state: absent
