---
- name: Deploy Personal Site
  hosts: all
  any_errors_fatal: true
  vars:
    timezone: America/Chicago
    k8s_config: /etc/rancher/k3s/k3s.yaml
    k8s_namespace: "{{ lookup('env', 'K8S_NAMESPACE') }}"
    app_image: "{{ lookup('env', 'APP_IMAGE') }}"
    app_hostname: "{{ lookup('env', 'APP_HOSTNAME') }}"
    # Used to run the image
    hugo_baseurl: "{{ lookup('env', 'HUGO_BASEURL') }}"
    hugo_title: "{{ lookup('env', 'HUGO_TITLE') }}"
    hugo_params_author: "{{ lookup('env', 'HUGO_PARAMS_AUTHOR') }}"
    hugo_params_description: "{{ lookup('env', 'HUGO_PARAMS_DESCRIPTION') }}"
    hugo_params_keywords: "{{ lookup('env', 'HUGO_PARAMS_KEYWORDS') }}"
    hugo_params_info: "{{ lookup('env', 'HUGO_PARAMS_INFO') }}"
    hugo_params_avatarurl: "{{ lookup('env', 'HUGO_PARAMS_AVATARURL') }}"
    hugo_params_colorscheme: "{{ lookup('env', 'HUGO_PARAMS_COLORSCHEME') }}"
    hugo_params_umami_enabled: "{{ lookup('env', 'HUGO_PARAMS_UMAMI_ENABLED') }}"
    hugo_params_umami_websiteid: "{{ lookup('env', 'HUGO_PARAMS_UMAMI_WEBSITEID') }}"
    hugo_params_umami_jslocation: "{{ lookup('env', 'HUGO_PARAMS_UMAMI_JSLOCATION') }}"
    hugo_social_email: "{{ lookup('env', 'HUGO_SOCIAL_EMAIL') }}"
    hugo_social_linkedin: "{{ lookup('env', 'HUGO_SOCIAL_LINKEDIN') }}"
    hugo_social_github: "{{ lookup('env', 'HUGO_SOCIAL_GITHUB') }}"
    hugo_resume: "{{ lookup('env', 'HUGO_RESUME') }}"
  tasks:
    - name: Install pip packages
      pip:
        name:
          - kubernetes
          - openshift

    - name: Create directory to upload k8s config to
      file:
        path: /root/deployments
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Upload k8s config
      template:
        src: app.yml.j2
        dest: /root/deployments/app.yml
        owner: root
        group: root
        mode: 0644

    - name: Load app to k8s
      k8s:
        kubeconfig: "{{ k8s_config }}"
        src: /root/deployments/app.yml
        state: present

    - name: Remove k8s config
      ansible.builtin.file:
        path: /root/deployments/app.yml
        state: absent
