#### Download Files from Cloud ####
FROM rclone/rclone AS cloud

# Arguments
ARG RCLONE_CONFIG_CLOUD_TYPE
ARG RCLONE_CONFIG_CLOUD_VENDOR
ARG RCLONE_CONFIG_CLOUD_URL
ARG RCLONE_CONFIG_CLOUD_USER
ARG RCLONE_CONFIG_CLOUD_PASS
ARG CLOUD_PATH_RESUME_FILENAME

# Environment variables
ENV RCLONE_CONFIG_CLOUD_TYPE=${RCLONE_CONFIG_CLOUD_TYPE}
ENV RCLONE_CONFIG_CLOUD_VENDOR=${RCLONE_CONFIG_CLOUD_VENDOR}
ENV RCLONE_CONFIG_CLOUD_URL=${RCLONE_CONFIG_CLOUD_URL}
ENV RCLONE_CONFIG_CLOUD_USER=${RCLONE_CONFIG_CLOUD_USER}
ENV RCLONE_CONFIG_CLOUD_PASS=${RCLONE_CONFIG_CLOUD_PASS}
ENV CLOUD_PATH_RESUME_FILENAME=${CLOUD_PATH_RESUME_FILENAME}

# Dependencies
RUN mkdir -p /tmp/static

# Download files
RUN rclone copy cloud:"/Documents/Job Applications/$CLOUD_PATH_RESUME_FILENAME" /tmp/static/pdf
RUN rclone sync --create-empty-src-dirs cloud:"/Photos/Personal Site Images/" /tmp/static/images/


#### Build Static Files ####
FROM hugomods/hugo:dart-sass-git-non-root AS hugo

# Arguments
ARG CLOUD_PATH_RESUME_FILENAME
ARG HUGO_BASEURL
ARG HUGO_TITLE
ARG HUGO_PARAMS_AUTHOR
ARG HUGO_PARAMS_DESCRIPTION
ARG HUGO_PARAMS_INFO
ARG HUGO_PARAMS_KEYWORDS
ARG HUGO_PARAMS_AVATARURL
ARG HUGO_PARAMS_COLORSCHEME
ARG HUGO_PARAMS_RYBBIT_ENABLED
ARG HUGO_PARAMS_RYBBIT_WEBSITEID
ARG HUGO_PARAMS_RYBBIT_JSLOCATION
ARG HUGO_PARAMS_EMAIL
ARG HUGO_PARAMS_LINKEDIN
ARG HUGO_PARAMS_GITHUB
ARG HUGO_RESUME

# Environment variables
ENV HUGO_BASEURL=${HUGO_BASEURL}
ENV HUGO_TITLE=${HUGO_TITLE}
ENV HUGO_PARAMS_AUTHOR=${HUGO_PARAMS_AUTHOR}
ENV HUGO_PARAMS_DESCRIPTION=${HUGO_PARAMS_DESCRIPTION}
ENV HUGO_PARAMS_INFO=${HUGO_PARAMS_INFO}
ENV HUGO_PARAMS_KEYWORDS=${HUGO_PARAMS_KEYWORDS}
ENV HUGO_PARAMS_AVATARURL=${HUGO_PARAMS_AVATARURL}
ENV HUGO_PARAMS_COLORSCHEME=${HUGO_PARAMS_COLORSCHEME}
ENV HUGO_PARAMS_RYBBIT_ENABLED=${HUGO_PARAMS_RYBBIT_ENABLED}
ENV HUGO_PARAMS_RYBBIT_WEBSITEID=${HUGO_PARAMS_RYBBIT_WEBSITEID}
ENV HUGO_PARAMS_RYBBIT_JSLOCATION=${HUGO_PARAMS_RYBBIT_JSLOCATION}
ENV HUGO_PARAMS_EMAIL=${HUGO_PARAMS_EMAIL}
ENV HUGO_PARAMS_LINKEDIN=${HUGO_PARAMS_LINKEDIN}
ENV HUGO_PARAMS_GITHUB=${HUGO_PARAMS_GITHUB}
ENV HUGO_RESUME=${CLOUD_PATH_RESUME_FILENAME}

# Copy files over
COPY --from=cloud /tmp/static /src/static
COPY archetypes /src/archetypes
COPY content /src/content
COPY layouts /src/layouts
COPY resources /src/resources
COPY themes /src/themes
COPY config.toml /src

# Generate static files
RUN hugo

#### Host Static Files via Nginx ####
FROM nginx
COPY --from=hugo /src/public /usr/share/nginx/html
