name: Build/Push App for Development
on:
  push:
    branches:
      - dev

env:
  RCLONE_CONFIG_CLOUD_TYPE: webdav
  RCLONE_CONFIG_CLOUD_VENDOR: nextcloud
  RCLONE_CONFIG_CLOUD_URL: ${{ vars.NEXTCLOUD_WEBDEV_URL }}
  RCLONE_CONFIG_CLOUD_USER: ${{ vars.NEXTCLOUD_USER }}
  RCLONE_CONFIG_CLOUD_PASS: ${{ secrets.NEXTCLOUD_API_TOKEN }}
  CLOUD_PATH_RESUME_FILENAME: ${{ vars.NEXTCLOUD_PATH_RESUME_FILENAME }}
  HUGO_BASEURL: ${{ vars.TEST_SITE_BASE_URL }}
  HUGO_TITLE: ${{ vars.SITE_FULL_NAME }}
  HUGO_PARAMS_AUTHOR: ${{ vars.SITE_FULL_NAME }}
  HUGO_PARAMS_DESCRIPTION: ${{ vars.SITE_DESCRIPTION }}
  HUGO_PARAMS_INFO: Network/DevOps Engineer
  HUGO_PARAMS_KEYWORDS: blog,personal,devops,systems,administrator,network,networking
  HUGO_PARAMS_AVATARURL: images/logo.jpg
  HUGO_PARAMS_COLORSCHEME: dark
  HUGO_PARAMS_UMAMI_ENABLED: true
  HUGO_PARAMS_UMAMI_WEBSITEID: ${{ vars.TEST_SITE_UMAMI_WEBSITEID }}
  HUGO_PARAMS_UMAMI_JSLOCATION: ${{ vars.SITE_UMAMI_JSLOCATION }}
  HUGO_PARAMS_EMAIL: ${{ vars.SITE_EMAIL_ADDRESS }}
  HUGO_PARAMS_LINKEDIN: ${{ vars.SITE_LINKEDIN_URL }}
  HUGO_PARAMS_GITHUB: ${{ vars.SITE_GITHUB_URL }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Login to VPS ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.VPS_ACR_URL }}
          username: ${{ vars.VPS_ACR_USERNAME }}
          password: ${{ secrets.VPS_ACR_PASSWORD }}

      - name: Build & Push to VPS ACR
        run: |
          docker build \
            --tag ${{ vars.VPS_ACR_URL }}/${{ vars.VPS_ACR_USERNAME }}/${{ steps.meta.outputs.REPO_NAME }}:dev .
          docker push ${{ vars.VPS_ACR_URL }}/${{ vars.VPS_ACR_USERNAME }}/${{ steps.meta.outputs.REPO_NAME }}:dev
