---
- name: Deploy Personal Site
  hosts: all
  any_errors_fatal: true
  vars:
    timezone: America/Chicago
    k8s_host: "{{ lookup('env', 'K8S_HOST') }}"
    k8s_config: /etc/rancher/k3s/k3s.yaml
    app_name: "{{ lookup('env', 'APP_K8S_NAME') }}"
    app_image: "{{ lookup('env', 'APP_IMAGE') }}"
    app_hostname: "{{ lookup('env', 'APP_K8S_HOSTNAME') }}"
    app_ingress: "{{ lookup('env', 'APP_K8S_INGRESS') }}"
  tasks:
    - name: Install pip packages
      pip:
        name:
          - kubernetes
          - openshift

    - name: Create directory to upload k8s config to
      file:
        path: /root/deployments
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Upload k8s config
      template:
        src: app.yml.j2
        dest: /root/deployments/app.yml
        owner: root
        group: root
        mode: 0644

    - name: Load app to k8s
      k8s:
        host: "{{ k8s_host }}"
        validate_certs: no
        kubeconfig: "{{ k8s_config }}"
        src: /root/deployments/app.yml
        state: present

    - name: Remove k8s config
      ansible.builtin.file:
        path: /root/deployments/app.yml
        state: absent
